databases:
  - name: a-buydb  # This is Render's reference name, can keep hyphens
    plan: free
    databaseName: a_buy  # Changed to underscore
    user: a_buy_user    # Changed to underscore

services:
  - type: web
    plan: free
    name: A-buy
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn A-buy.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: a-buydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
